---

- name: Install chromium
  apt:
    name: "chromium-browser"
    state: present
  become: yes
  tags: [install]
  when: chrome_flavor == "chromium"

- name: Download google-chrome
  get_url:
    url: "{{ google_chrome_download_url }}"
    dest: /tmp/google-chrome.deb
  tags: [install]
  when: chrome_flavor == "google-chrome"

- name: Install google-chrome
  apt:
    deb: "/tmp/google-chrome.deb"
  become: yes
  tags: [install]
  when: chrome_flavor == "google-chrome"

- name: Setup skel directory
  file:
    path: "/etc/skel/Desktop"
    state: directory
    mode: 0755
  when: chrome_install_desktop_skel
  become: yes
  tags: [config]

- name: Copy .desktop file
  template:
    src:  "chrome.desktop"
    dest: "/etc/skel/Desktop/{{ chrome_desktop_file_name }}.desktop"
    mode: "0751"
  when: chrome_install_desktop_skel
  become: yes
  tags: [config]

- name: Remove deb file after installation
  file:
    path: "/tmp/google-chrome.deb"
    state: absent
  tags: [cleanup]
  when: chrome_flavor == "google-chrome"

